sudo: false

language: node_js

matrix:
  include:
    - node_js: "node"
      env: NPM_RUN_SCRIPT=test
    - node_js: "9"
      env: NODE_ENV=production
    - node_js: "8"
      env: NODE_ENV=production
    - node_js: "7"
      env: NODE_ENV=production
    - node_js: "6"
      env: NODE_ENV=production
    - node_js: "5"
      env: NODE_ENV=production
    - node_js: "4"
      env: NODE_ENV=production

install:
  - npm install

script:
  - npm run ${NPM_RUN_SCRIPT:-test:spec}
