os: linux
dist: bionic

language: node_js

jobs:
  include:
    - node_js: 'node'
      env: NPM_PACK=yes NPM_RUN_LINT=yes
    - node_js: '12'
    - node_js: '10'
    - node_js: '8'

install:
  - set -e
  - npm install

script:
  - if [ -n "$NPM_RUN_LINT" ]; then npm run lint; fi
  - if [ -n "$NPM_PACK" ]; then npm pack; fi
  - npm run test:spec
  - git diff --stat --exit-code
  - for f in $(git ls-files --others --exclude-standard); do git diff --no-index --stat --exit-code /dev/null $next; done
